# Units:
# distance [m], speed [m/s], acceleration [m/s^2]

CARLA:
  DT: 0.1                                                      # Set to -1 for variable time-step (real-world simulation)
  LANE_WIDTH: 3.5
  MAX_S: 3000                                                  # [int] max frenet s value available in global route
  D_MAX_S: 200
  CAR_LENGTH: 5.00                                              # the length of vehicle Tesla Model3
  CAR_WIDTH: 2.00                                               # the width of vehicle Tesla Model3

POLICY:
  NAME: DDPG                                                    # DDPG/TRPO/PPO2/A2C
  NET: CNN                                                      # MLP/CNN/LSTM - DDPG does not have LSTM policy
  CNN_EXTRACTOR: sequence_1d_cnn_ego_bypass_tc                  # nature_cnn/sequence_1d_cnn/sequence_1d_cnn_ego_bypass_tc
  ACTION_NOISE: 0.5                                             # DDPG only
  PARAM_NOISE_STD: 0.0                                          # DDPG only

GYM_ENV:
  FIXED_REPRESENTATION: True                                    # actors's states have fixed positions in the observation tensor
  TRACK_LENGTH: 750                                            # [int] distance to travel on s axis before terminating the episode. Must be less than CARLA.MAX_S - 50
  TARGET_SPEED: 13.89                                           # Ego's target speed
#  MAX_SPEED: 19.5
#  MIN_SPEED: 13.5
  MAX_SPEED: 15
  MIN_SPEED: 9
  R_MAX_SPEED: 5
  R_MIN_SPEED: -5
  MAX_ACC: 1
  MIN_ACC: -2
  MAX_DACC: 200
  MIN_DACC: -200
#  MAX_ACC: 6.878                                                # equivalent to 24.7608 km/h.s for Tesla model 3
  LOOK_BACK: 30                                                 # [int] Steps to look back at last path for observation sequence vector
  TIME_STEP: 4                                                  # [int] Steps to look back at last path for observation sequence vector (TIME_STEP + 1)
  LOOP_BREAK: 30                                                # NOT USED [int] steps to break path following while loop  - must be greater than LOOK_BACK
  DISTN_FRM_VHCL_AHD: 200                                       # Effective distance to keep from vehicle ahead for IDM

RL:
  W_SPEED: 5                                                    # Speed Error Resolution
  W_R_SPEED: 10                                                 # Speed Reward Magnitude (w*r_speed)
  Low_SPEED_REWARD: 0.3                                         # Low Speed reward
  Middle_SPEED_REWARD: 4                                          # Middle Speed reward
  High_SPEED_REWARD: 0.3                                        # High Speed reward
  Low_ACC_REWARD: 0.3                                           # Low Acc reward
  High_ACC_REWARD: 0.3                                          # High Acc reward
  Low_DELTA_ACC_REWARD: 4                                       # Low DAcc reward
  High_DELTA_ACC_REWARD: 0.3                                    # High DAcc reward
  LANE_CHANGE_PENALTY: 0.2                                      # Unnecesary Lane Change Penalty
  LANE_CHANGE_REWARD: 2                                         # Meaningful Lane Change Reward (w*speed_reward)
  OFF_THE_ROAD: -10                                             # Off-the-road attempt penalty
  COLLISION: -1000                                             # Collison penalty

LOCAL_PLANNER:
  MIN_SPEED: 6 # 5.56                                       # Allowed min speed for ego vehicle; RL's -1 action maps to this value
#  MAX_SPEED: 20                                              # Allowed max speed for ego vehicle; RL's 1 action maps to this value
  MAX_SPEED: 15.5

TRAFFIC_MANAGER:
  N_SPAWN_CARS: 5                        # number of cars spawned at each episode
  MIN_SPEED: 6.56  #10.56                                               # Min speed for actors in random traffic
  MAX_SPEED: 9.11        # 13.11                                        # Max speed for actors in random traffic
  MAX_ACC: 1.5  # 2
  MIN_ACC: -1.5
  INIT_ACTION: [-1,0,0,0]                                 # 初始的动作，用于reset使用，是一个和action维度一样的变量
  MIN_SPEED_2: 6.33 #8.33
  MAX_SPEED_2: 9.11    # 11.11

OTHER_INFOMATION:
  CONTROL_MODE: 0                           # 0代表通过steer\throttle\brake控制车辆；1代表通过right_change\left_change\speed_up\brake控制车辆; 2代表通过连续的steer/throttle/brake控制车辆。
  AV_DIFFERENCE: -40                           # 自然驾驶状态下AV的速度与限速的差别，AV的期望速度足够高才会换道
  BV_DIFFERENCE: [-10,-5,0,5,10]                           # 自然监事状态下BV的速度与限速的差别
  INIT_TIME_STEP:  20                     # 回放场景的时间起点
  DATA_NAME: 'case12.xls'        # 记录场景的文件
  ADVERSARIAL: 0              # 回放初始状态的场景是否要采用对抗环境，0代表自然，1代表对抗
  RECORD: 0                 # 1代表在测试过程中记录场景，0代表不记录场景，
  REPLAY_MODE: 1     # 0 代表从起点开始不回放 ; 1 回放初始位置和策略 ； 2代表回放记录轨迹,只针对环境3; 3代表周车回放轨迹，自车用策略控制，只针对环境3